services:
  db:
    image: mysql:8.0.23
    environment:
      MYSQL_ROOT_PASSWORD: redwing
    ports:
      - "3306:3306"
    volumes:
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
